/**
 * LaTeX autocompletion command list for Monaco editor.
 * Covers document structure, text formatting, math, Greek letters,
 * environments, packages, and common utility commands.
 *
 * Total: 162 entries
 */
export const LATEX_COMMANDS: string[] = [
  // ---- Document structure ----
  '\\documentclass{',
  '\\begin{',
  '\\end{',
  '\\section{',
  '\\subsection{',
  '\\subsubsection{',
  '\\paragraph{',
  '\\subparagraph{',
  '\\chapter{',
  '\\part{',
  '\\appendix',
  '\\title{',
  '\\author{',
  '\\date{',
  '\\maketitle',
  '\\tableofcontents',
  '\\listoffigures',
  '\\listoftables',
  '\\frontmatter',
  '\\mainmatter',
  '\\backmatter',

  // ---- Packages & includes ----
  '\\usepackage{',
  '\\include{',
  '\\input{',
  '\\includegraphics{',
  '\\bibliography{',
  '\\bibliographystyle{',
  '\\addbibresource{',

  // ---- Cross-references ----
  '\\label{',
  '\\ref{',
  '\\eqref{',
  '\\pageref{',
  '\\cite{',
  '\\citep{',
  '\\citet{',
  '\\nocite{',
  '\\index{',
  '\\glossary{',

  // ---- Text formatting ----
  '\\textbf{',
  '\\textit{',
  '\\underline{',
  '\\emph{',
  '\\textrm{',
  '\\textsf{',
  '\\texttt{',
  '\\textsc{',
  '\\textsl{',
  '\\textup{',
  '\\textcolor{',
  '\\colorbox{',
  '\\fcolorbox{',
  '\\pagecolor{',

  // ---- Font size ----
  '\\tiny',
  '\\scriptsize',
  '\\footnotesize',
  '\\small',
  '\\normalsize',
  '\\large',
  '\\Large',
  '\\LARGE',
  '\\huge',
  '\\Huge',

  // ---- Paragraph & page ----
  '\\newline',
  '\\newpage',
  '\\clearpage',
  '\\linebreak',
  '\\nolinebreak',
  '\\pagebreak',
  '\\nopagebreak',
  '\\par',
  '\\indent',
  '\\noindent',
  '\\centering',
  '\\raggedright',
  '\\raggedleft',

  // ---- Spacing ----
  '\\hspace{',
  '\\vspace{',
  '\\setlength{',
  '\\addtolength{',
  '\\settowidth{',
  '\\settoheight{',
  '\\settodepth{',
  '\\stretch{',
  '\\fill',
  '\\linewidth',
  '\\textwidth',
  '\\columnwidth',
  '\\pageheight',
  '\\baselineskip',
  '\\parindent',
  '\\parskip',

  // ---- Footnotes & marginalia ----
  '\\footnote{',
  '\\footnotetext{',
  '\\footnotemark',
  '\\marginpar{',

  // ---- Lists ----
  '\\item',
  '\\item[',

  // ---- Tables ----
  '\\caption{',
  '\\captionof{',
  '\\multicolumn{',
  '\\multirow{',
  '\\hline',
  '\\cline{',
  '\\toprule',
  '\\midrule',
  '\\bottomrule',
  '\\figurename',
  '\\tablename',

  // ---- Custom commands ----
  '\\newcommand{',
  '\\renewcommand{',
  '\\providecommand{',
  '\\def{',
  '\\newenvironment{',
  '\\renewenvironment{',
  '\\newlength{',
  '\\newcounter{',
  '\\setcounter{',
  '\\stepcounter{',
  '\\addtocounter{',
  '\\value{',
  '\\arabic{',
  '\\roman{',
  '\\Roman{',
  '\\alph{',
  '\\Alph{',
  '\\fnsymbol{',

  // ---- Conditionals ----
  '\\ifluatex',
  '\\ifxetex',
  '\\ifpdftex',
  '\\else',
  '\\fi',
  '\\newif',

  // ---- Verbatim & code ----
  '\\verb|',
  '\\verbatiminput{',
  '\\lstinputlisting{',
  '\\mint{',

  // ---- Boxes ----
  '\\mbox{',
  '\\makebox{',
  '\\fbox{',
  '\\framebox{',
  '\\parbox{',
  '\\minipage{',
  '\\raisebox{',
  '\\rule{',

  // ---- Floats ----
  '\\floatstyle{',
  '\\newfloat{',
  '\\floatname{',
  '\\listof{',

  // ---- Math: operators ----
  '\\frac{',
  '\\dfrac{',
  '\\tfrac{',
  '\\sqrt{',
  '\\overline{',
  '\\underline{',
  '\\hat{',
  '\\bar{',
  '\\dot{',
  '\\ddot{',
  '\\tilde{',
  '\\vec{',
  '\\overrightarrow{',
  '\\overleftarrow{',
  '\\widehat{',
  '\\widetilde{',
  '\\overbrace{',
  '\\underbrace{',
  '\\stackrel{',
  '\\overset{',
  '\\underset{',

  // ---- Math: big operators ----
  '\\sum',
  '\\prod',
  '\\coprod',
  '\\int',
  '\\iint',
  '\\iiint',
  '\\oint',
  '\\lim',
  '\\limsup',
  '\\liminf',
  '\\sup',
  '\\inf',
  '\\max',
  '\\min',
  '\\bigcup',
  '\\bigcap',
  '\\bigsqcup',
  '\\bigoplus',
  '\\bigotimes',
  '\\bigodot',
  '\\bigvee',
  '\\bigwedge',
  '\\biguplus',

  // ---- Math: styles ----
  '\\mathrm{',
  '\\mathbf{',
  '\\mathit{',
  '\\mathsf{',
  '\\mathtt{',
  '\\mathcal{',
  '\\mathbb{',
  '\\mathfrak{',
  '\\mathscr{',

  // ---- Math: delimiters ----
  '\\left(',
  '\\right)',
  '\\left[',
  '\\right]',
  '\\left\\{',
  '\\right\\}',
  '\\left|',
  '\\right|',
  '\\left\\|',
  '\\right\\|',
  '\\left\\langle',
  '\\right\\rangle',
  '\\big(',
  '\\big[',
  '\\big\\{',
  '\\Big(',
  '\\Bigg(',

  // ---- Math: binary operators ----
  '\\cdot',
  '\\times',
  '\\div',
  '\\pm',
  '\\mp',
  '\\circ',
  '\\bullet',
  '\\oplus',
  '\\ominus',
  '\\otimes',
  '\\oslash',
  '\\odot',
  '\\dagger',
  '\\ddagger',
  '\\star',
  '\\ast',
  '\\triangleleft',
  '\\triangleright',
  '\\bigtriangleup',
  '\\bigtriangledown',
  '\\wedge',
  '\\vee',
  '\\cap',
  '\\cup',
  '\\setminus',
  '\\wr',
  '\\diamond',
  '\\amalg',

  // ---- Math: relations ----
  '\\leq',
  '\\geq',
  '\\neq',
  '\\approx',
  '\\equiv',
  '\\sim',
  '\\simeq',
  '\\cong',
  '\\propto',
  '\\perp',
  '\\parallel',
  '\\mid',
  '\\ll',
  '\\gg',
  '\\doteq',
  '\\models',
  '\\prec',
  '\\succ',
  '\\preceq',
  '\\succeq',
  '\\bowtie',
  '\\asymp',
  '\\smile',
  '\\frown',

  // ---- Math: arrows ----
  '\\rightarrow',
  '\\leftarrow',
  '\\Rightarrow',
  '\\Leftarrow',
  '\\Leftrightarrow',
  '\\leftrightarrow',
  '\\longrightarrow',
  '\\longleftarrow',
  '\\Longrightarrow',
  '\\Longleftarrow',
  '\\Longleftrightarrow',
  '\\longleftrightarrow',
  '\\uparrow',
  '\\downarrow',
  '\\Uparrow',
  '\\Downarrow',
  '\\Updownarrow',
  '\\updownarrow',
  '\\nearrow',
  '\\searrow',
  '\\swarrow',
  '\\nwarrow',
  '\\mapsto',
  '\\longmapsto',
  '\\hookrightarrow',
  '\\hookleftarrow',
  '\\rightharpoonup',
  '\\rightharpoondown',
  '\\leftharpoonup',
  '\\leftharpoondown',
  '\\rightleftharpoons',
  '\\to',
  '\\gets',

  // ---- Math: misc symbols ----
  '\\infty',
  '\\partial',
  '\\nabla',
  '\\forall',
  '\\exists',
  '\\nexists',
  '\\in',
  '\\notin',
  '\\ni',
  '\\subset',
  '\\supset',
  '\\subseteq',
  '\\supseteq',
  '\\sqsubset',
  '\\sqsupset',
  '\\sqsubseteq',
  '\\sqsupseteq',
  '\\emptyset',
  '\\varnothing',
  '\\Re',
  '\\Im',
  '\\aleph',
  '\\hbar',
  '\\ell',
  '\\wp',
  '\\top',
  '\\bot',
  '\\angle',
  '\\triangle',
  '\\square',
  '\\lozenge',
  '\\clubsuit',
  '\\diamondsuit',
  '\\heartsuit',
  '\\spadesuit',
  '\\sharp',
  '\\flat',
  '\\natural',
  '\\neg',
  '\\lnot',
  '\\land',
  '\\lor',
  '\\vdash',
  '\\dashv',

  // ---- Math: dots ----
  '\\ldots',
  '\\cdots',
  '\\vdots',
  '\\ddots',
  '\\dots',

  // ---- Greek lowercase ----
  '\\alpha',
  '\\beta',
  '\\gamma',
  '\\delta',
  '\\epsilon',
  '\\varepsilon',
  '\\zeta',
  '\\eta',
  '\\theta',
  '\\vartheta',
  '\\iota',
  '\\kappa',
  '\\lambda',
  '\\mu',
  '\\nu',
  '\\xi',
  '\\pi',
  '\\varpi',
  '\\rho',
  '\\varrho',
  '\\sigma',
  '\\varsigma',
  '\\tau',
  '\\upsilon',
  '\\phi',
  '\\varphi',
  '\\chi',
  '\\psi',
  '\\omega',

  // ---- Greek uppercase ----
  '\\Gamma',
  '\\Delta',
  '\\Theta',
  '\\Lambda',
  '\\Xi',
  '\\Pi',
  '\\Sigma',
  '\\Upsilon',
  '\\Phi',
  '\\Psi',
  '\\Omega',

  // ---- Hyperlinks ----
  '\\href{',
  '\\url{',

  // ---- Theorem-like ----
  '\\theoremstyle{',
  '\\newtheorem{',
];

/**
 * Register LaTeX commands as Monaco autocompletion suggestions.
 * Call this once after the Monaco editor instance is ready.
 */
export function registerLatexCompletions(monacoInstance: typeof import('monaco-editor')): void {
  monacoInstance.languages.registerCompletionItemProvider('latex', {
    triggerCharacters: ['\\'],
    provideCompletionItems(model, position) {
      const word = model.getWordUntilPosition(position);
      const range = {
        startLineNumber: position.lineNumber,
        endLineNumber: position.lineNumber,
        startColumn: word.startColumn,
        endColumn: word.endColumn,
      };

      const suggestions = LATEX_COMMANDS.map((cmd) => {
        const label = cmd.endsWith('{') ? cmd.slice(0, -1) : cmd;
        const hasBrace = cmd.endsWith('{');
        return {
          label,
          kind: monacoInstance.languages.CompletionItemKind.Function,
          insertText: hasBrace ? `${cmd}$1}` : cmd,
          insertTextRules: monacoInstance.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
          detail: 'LaTeX',
        };
      });

      return { suggestions };
    },
  });
}
